# Generated by Django 6.0.1 on 2026-02-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My LMS', max_length=200)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('default_meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('default_meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('zarinpal_merchant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('idpay_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_public_key', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('sms_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('sms_sender_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
