# Generated by Django 6.0.1 on 2026-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponredemption',
            options={},
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
