# Generated by Django 6.0.1 on 2026-02-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='card_number',
            field=models.CharField(blank=True, help_text='شماره کارت (اختیاری)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='sheba_number',
            field=models.CharField(blank=True, help_text='شماره شبا بدون IR', max_length=26, null=True),
        ),
    ]
