# Generated by Django 6.0.1 on 2026-02-22 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructorprofile_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('type', models.CharField(default='مدرس', max_length=100)),
                ('location', models.CharField(default='دورکاری', max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('national_card_front', models.ImageField(blank=True, null=True, upload_to='teacher_docs/national_card/')),
                ('national_card_back', models.ImageField(blank=True, null=True, upload_to='teacher_docs/national_card/')),
                ('medical_card_front', models.ImageField(blank=True, null=True, upload_to='teacher_docs/medical_card/')),
                ('medical_card_back', models.ImageField(blank=True, null=True, upload_to='teacher_docs/medical_card/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='teacher_docs/resume/')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
