# Generated by Django 6.0.1 on 2026-02-22 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobopening_teacherapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مدرس',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مدرس',
            },
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='accounts.instructorcategory'),
        ),
    ]
