# Generated by Django 6.0.1 on 2026-02-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_enrollment_course'),
        ('courses', '0002_remove_courses_course_teacher_course_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
