# Generated by Django 6.0.1 on 2026-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('completed', 'تکمیل شده')], default='draft', max_length=20),
        ),
    ]
