# Generated by Django 6.0.1 on 2026-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='receipt',
            field=models.FileField(blank=True, help_text='رسید پرداخت به مدرس (اختیاری)', null=True, upload_to='payout_receipts/'),
        ),
    ]
